# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target '袋鼠记' do

#########  Tool  #########
pod 'YYKit'   # YYKit
pod 'AFNetworking' #网络框架
pod 'Masonry'  #自动布局
pod 'IQKeyboardManager'  #键盘管理
pod 'MBProgressHUD’ # 指示器
pod 'MJRefresh'  # 刷新
#pod 'MJExtension'
pod 'FMDB'  # 数据库
pod 'KVOController' # FaceBook KVO（优雅的代替系统原生的KVO）
#pod 'BlocksKit'
#pod 'iCarousel'
pod "QCloudCOSV4" # 云存储



#########  UIKit  #########
#pod 'UAProgressView' # 环形进度条
#pod 'TXScrollLabelView' # 文字滚动的label
#pod 'TTTAttributedLabel'   # 富文本
pod 'SDCycleScrollView'  # 轮播banner
pod 'UICollectionViewLeftAlignedLayout'  # UICollectionView左对齐布局
pod 'CHTCollectionViewWaterfallLayout'   # 瀑布流


#########  Category  #########
#pod 'UITableView+FDTemplateLayoutCell' # 缓存tableViewCell的高度
#pod 'libextobjc'  # 非常强大的Objective-C库的扩展


end
